### PR TITLE
upgrade controller-runtime to v0.8.0

### PR DESCRIPTION
**Pull request by morvencao**
/assign @horis233

### CODE REVIEW

**Review by horis233 — APPROVED** [review]
/lgtm

**Comment by horis233** [comment]
@morvencao PR is merged, create a release tag v0.3.0 for picking up this PR https://github.com/IBM/controller-filtered-cache/releases/tag/v0.3.0

**Comment by marcolan018** [comment]
@horis233 thanks

**Comment by morvencao** [comment]
thanks @horis233

**Pull request merged**
